package enum

type CurrencyName string

const (
	UnitedStatesDollar       CurrencyName = "United States Dollar"
	Euro                     CurrencyName = "Euro"
	BritishPound             CurrencyName = "British Pound Sterling"
	JapaneseYen              CurrencyName = "Japanese Yen"
	CanadianDollar           CurrencyName = "Canadian Dollar"
	AustralianDollar         CurrencyName = "Australian Dollar"
	SwissFranc               CurrencyName = "Swiss Franc"
	ChineseYuan              CurrencyName = "Chinese Yuan"
	SwedishKrona             CurrencyName = "Swedish Krona"
	NewZealandDollar         CurrencyName = "New Zealand Dollar"
	MexicanPeso              CurrencyName = "Mexican Peso"
	SingaporeDollar          CurrencyName = "Singapore Dollar"
	HongKongDollar           CurrencyName = "Hong Kong Dollar"
	NorwegianKrone           CurrencyName = "Norwegian Krone"
	SouthKoreanWon           CurrencyName = "South Korean Won"
	TurkishLira              CurrencyName = "Turkish Lira"
	RussianRuble             CurrencyName = "Russian Ruble"
	IndianRupee              CurrencyName = "Indian Rupee"
	BrazilianReal            CurrencyName = "Brazilian Real"
	SouthAfricanRand         CurrencyName = "South African Rand"
	DanishKrone              CurrencyName = "Danish Krone"
	PolishZloty              CurrencyName = "Polish Zloty"
	ThaiBaht                 CurrencyName = "Thai Baht"
	IndonesianRupiah         CurrencyName = "Indonesian Rupiah"
	TaiwaneseDollar          CurrencyName = "Taiwanese Dollar"
	MalaysianRinggit         CurrencyName = "Malaysian Ringgit"
	CzechKoruna              CurrencyName = "Czech Koruna"
	HungarianForint          CurrencyName = "Hungarian Forint"
	PhilippinePeso           CurrencyName = "Philippine Peso"
	UnitedArabEmiratesDirham CurrencyName = "United Arab Emirates Dirham"
	SaudiRiyal               CurrencyName = "Saudi Riyal"
	BahrainiDinar            CurrencyName = "Bahraini Dinar"
	EgyptianPound            CurrencyName = "Egyptian Pound"
	ChileanPeso              CurrencyName = "Chilean Peso"
	ColombianPeso            CurrencyName = "Colombian Peso"
	PakistaniRupee           CurrencyName = "Pakistani Rupee"
	RomanianLeu              CurrencyName = "Romanian Leu"
	PeruvianSol              CurrencyName = "Peruvian Sol"
	JordanianDinar           CurrencyName = "Jordanian Dinar"
	QatariRiyal              CurrencyName = "Qatari Riyal"
	OmaniRial                CurrencyName = "Omani Rial"
	UkrainianHryvnia         CurrencyName = "Ukrainian Hryvnia"
	LebanesePound            CurrencyName = "Lebanese Pound"
	VietnameseDong           CurrencyName = "Vietnamese Dong"
	NigerianNaira            CurrencyName = "Nigerian Naira"
	KazakhstaniTenge         CurrencyName = "Kazakhstani Tenge"
	BangladeshiTaka          CurrencyName = "Bangladeshi Taka"
	KenyanShilling           CurrencyName = "Kenyan Shilling"
	UgandanShilling          CurrencyName = "Ugandan Shilling"
)
