package enum

type CurrencyCode string

const (
	USD CurrencyCode = "USD"
	EUR CurrencyCode = "EUR"
	GBP CurrencyCode = "GBP"
	JPY CurrencyCode = "JPY"
	CAD CurrencyCode = "CAD"
	AUD CurrencyCode = "AUD"
	CHF CurrencyCode = "CHF"
	CNY CurrencyCode = "CNY"
	SEK CurrencyCode = "SEK"
	NZD CurrencyCode = "NZD"
	MXN CurrencyCode = "MXN"
	SGD CurrencyCode = "SGD"
	HKD CurrencyCode = "HKD"
	NOK CurrencyCode = "NOK"
	KRW CurrencyCode = "KRW"
	TRY CurrencyCode = "TRY"
	RUB CurrencyCode = "RUB"
	INR CurrencyCode = "INR"
	BRL CurrencyCode = "BRL"
	ZAR CurrencyCode = "ZAR"
	DKK CurrencyCode = "DKK"
	PLN CurrencyCode = "PLN"
	THB CurrencyCode = "THB"
	IDR CurrencyCode = "IDR"
	TWD CurrencyCode = "TWD"
	MYR CurrencyCode = "MYR"
	CZK CurrencyCode = "CZK"
	HUF CurrencyCode = "HUF"
	PHP CurrencyCode = "PHP"
	AED CurrencyCode = "AED"
	SAR CurrencyCode = "SAR"
	BHD CurrencyCode = "BHD"
	EGP CurrencyCode = "EGP"
	CLP CurrencyCode = "CLP"
	COP CurrencyCode = "COP"
	PKR CurrencyCode = "PKR"
	RON CurrencyCode = "RON"
	PEN CurrencyCode = "PEN"
	JOD CurrencyCode = "JOD"
	QAR CurrencyCode = "QAR"
	OMR CurrencyCode = "OMR"
	UAH CurrencyCode = "UAH"
	LBP CurrencyCode = "LBP"
	VND CurrencyCode = "VND"
	NGN CurrencyCode = "NGN"
	KZT CurrencyCode = "KZT"
	BDT CurrencyCode = "BDT"
	KES CurrencyCode = "KES"
	UGX CurrencyCode = "UGX"
)
