package enum

type CurrencySymbol string

const (
	DollarSymbol      CurrencySymbol = "$"
	EuroSymbol        CurrencySymbol = "€"
	PoundSymbol       CurrencySymbol = "£"
	YenSymbol         CurrencySymbol = "¥"
	CADSymbol         CurrencySymbol = "$"
	AUDSymbol         CurrencySymbol = "$"
	FrancSymbol       CurrencySymbol = "₣"
	YuanSymbol        CurrencySymbol = "¥"
	KronaSymbol       CurrencySymbol = "kr"
	NZDSymbol         CurrencySymbol = "$"
	PesoSymbol        CurrencySymbol = "$"
	SGDSymbol         CurrencySymbol = "$"
	HKDSymbol         CurrencySymbol = "$"
	KroneSymbol       CurrencySymbol = "kr"
	WonSymbol         CurrencySymbol = "₩"
	LiraSymbol        CurrencySymbol = "₺"
	RubleSymbol       CurrencySymbol = "₽"
	RupeeSymbol       CurrencySymbol = "₹"
	RealSymbol        CurrencySymbol = "R$"
	RandSymbol        CurrencySymbol = "R"
	KroneDKSymbol     CurrencySymbol = "kr"
	ZlotySymbol       CurrencySymbol = "zł"
	BahtSymbol        CurrencySymbol = "฿"
	RupiahSymbol      CurrencySymbol = "Rp"
	NTDSymbol         CurrencySymbol = "$"
	RinggitSymbol     CurrencySymbol = "RM"
	KorunaSymbol      CurrencySymbol = "Kč"
	ForintSymbol      CurrencySymbol = "Ft"
	PesoPHSymbol      CurrencySymbol = "₱"
	DirhamSymbol      CurrencySymbol = "د.إ"
	RiyalSymbol       CurrencySymbol = "﷼"
	DinarBHDSymbol    CurrencySymbol = ".د.ب"
	PoundEGSymbol     CurrencySymbol = "£"
	PesoCLSymbol      CurrencySymbol = "$"
	PesoCOPSymbol     CurrencySymbol = "$"
	RupeePKSymbol     CurrencySymbol = "₨"
	LeuSymbol         CurrencySymbol = "lei"
	SolSymbol         CurrencySymbol = "S/."
	DinarJODSymbol    CurrencySymbol = "JD"
	RiyalQARSymbol    CurrencySymbol = "﷼"
	RialSymbol        CurrencySymbol = "ر.ع."
	HryvniaSymbol     CurrencySymbol = "₴"
	PoundLBSymbol     CurrencySymbol = "£"
	DongSymbol        CurrencySymbol = "₫"
	NairaSymbol       CurrencySymbol = "₦"
	TengeSymbol       CurrencySymbol = "₸"
	TakaSymbol        CurrencySymbol = "৳"
	ShillingKESymbol  CurrencySymbol = "Sh"
	ShillingUGXSymbol CurrencySymbol = "Sh"
)
